### PR TITLE
Old code fragments contamination

### PR DESCRIPTION
**Pull request by z-ichinohe**
I'm so sorry for the contamination caused by my poor merge action and the lack of check with build tests. I removed the old code fragments and it's built successfully with mac and ubuntu and works well for me.

### CODE REVIEW

**Comment by amaelkady** [comment]
@z-ichinohe thanks. I will check the code and let you know.

**Comment by z-ichinohe** [comment]
I noticed that the documentations have variable names conflicts. They have "Up_pos" and "dp_pos" originally. Moreover, I changed them in the line No.62 to 68. 

The conflicts in the documents and between the documents and error message would confuse the users. However, I think it doesn't need to coincide with the variable names used in the codes exactly. I think it should not be "posUp_0" but should be "posUp" for the sake of brevity. Those who want to see the source codes may notice that the initial value "posUp_0" is the initial value mentioned as "posUp" in the document and "posUp" is a current value. Those who don't see the source code don't have to notice that there are variables with "_0" and without that. Unifying them to "Up_pos" or "dp_pos" may be good. It can trouble the people seeing the source codes, but it might be few.

Which modification would be better? Let me know your opinion.

**Comment by amaelkady** [comment]
Yes, thanks, I just noticed that the documentation files were not updated. I just fixed the documentation notation. This was already fixed on the master OpenSees repo documentation.
No need to modify the notation to be consistent with the code. I believe the code is already understandable and any future modification would be conducted mostly bu us.

**Comment by z-ichinohe** [comment]
Thank you for you update. I agree that it's no need to modify the notation in the code.

**Pull request merged**
